### ISSUE TITLE
Understand and Visualize the Waypoint Predictions

### ISSUE THREAD

**Issue by animikhaich** [autonomousvision/carla_garage#14]
I am trying to visualize and understand the waypoint predictions from the TF++ model. 

I added the following piece of code to [team_code/sensor_agent.py](https://github.com/autonomousvision/carla_garage/blob/main/team_code/sensor_agent.py#L557) to try and visualize the Waypoints and the corresponding control translations via PID:

```py

# Print Controls
print(f"[Model] Throttle: {throttle} | Steer: {steer} | Brake: {brake}")

# Inits
fig = plt.figure()
canvas = fig.canvas
ax = fig.gca()

# Plotting
pts = np.squeeze(self.pred_wp.detach().cpu().numpy())
ax.scatter(pts[:, 0], pts[:, 1], cmap='viridis', c=range(pts.shape[0]), s=100)

# Visualization
ax.axis('off')
canvas.draw()
image_flat = np.frombuffer(canvas.tostring_rgb(), dtype='uint8')
image = image_flat.reshape(*reversed(canvas.get_width_height()), 3)
raw_rgb = tick_data['rgb'].squeeze().permute(1, 2, 0).cpu().numpy()
cv2.imshow('Image', raw_rgb.astype(np.uint8)[:,:,::-1]) # The RGB Input
cv2.imshow('waypoints', image) # The Waypoints Plot
cv2.waitKey(1)
```

I am trying to visualize the live waypoints either in a BEV space similar to [Figure 2(b) in the paper](https://arxiv.org/abs/2306.07957), or in the RGB camera similar to [this Video by Wayve](https://youtu.be/yFsNMKJOVck). 

However, when I plot the raw waypoint values, they don't correspond to the path ahead (as shown in the two images below, where the road is straight, yet the waypoint plots differ completely). 

Please explain the raw waypoint predictions of the model and how to interpret/visualize them. Also, if there is any transformation that needs to be done, please share a code snippet for the same. 

Thanks!

Screenshot 1:
![Screenshot from 2023-10-18 20-32-31](https://github.com/autonomousvision/carla_garage/assets/16799596/bee116dd-2519-48c9-85f2-65f6490b3ff3)

Screenshot 2:
![Screenshot from 2023-10-18 20-32-54](https://github.com/autonomousvision/carla_garage/assets/16799596/f323a1db-7010-4e99-b6c0-83b3f4f08aa2)

**Comment by Kait0** [comment]
I would recommend you use the existing visualization code by setting the [DEBUG_CHALLENGE](https://github.com/autonomousvision/carla_garage/blob/8bb143807ee9df6c1524fe72043ea687ad2ec2aa/team_code/sensor_agent.py#L84C45-L84C60) environment flag to 1.
As well as a `SAVE_PATH` which tell the code where to save the generated images.
