### ISSUE TITLE
Has NC TF been released?

### ISSUE THREAD

**Issue by wheltz** [autonomousvision/carla_garage#15]
Hello, this is very helpful work. I would like to ask if the published code contains the implementation of NC conditioned model of TF in the paper. I want to do some extension work, thank you very much

**Comment by Kait0** [comment]
Yes all experiments in the paper can be run with the released codebase.
The option for conditioning signal is `--use_tp 0` to remove the target point and `--use_discrete_command 1` to use the navigational command.

**Comment by Wolfybox** [comment]
> Yes all experiments in the paper can be run with the released codebase. The option for conditioning signal is `--use_tp 0` to remove the target point and `--use_discrete_command 1` to use the navigational command.

![2023-11-07_16-02](https://github.com/autonomousvision/carla_garage/assets/32531785/6b7ee7e0-28bb-4d3b-8ffe-c464fa818432)

hello, I found that all provided pretrained models are trained with use_tp=1. Is it ok to test them with option use_tp=0?
