### ISSUE TITLE
if the code evaluate on the Carla leaderboard

### ISSUE THREAD

**Issue by raozhongyu** [autonomousvision/carla_garage#2]
Thanks for your great job! I wonder if the code evaluate on the Carla leaderboard?

**Comment by Kait0** [comment]
yes, you can find the discussion on the CARLA leaderboard in the appendix of the paper.
Scripts for submitting to the leaderboard are available [here](https://github.com/autonomousvision/carla_garage/tree/main/tools).
Will add documentation on how to use them next week.

**Comment by raozhongyu** [comment]
I get it. Thanks a lot.
