### ISSUE TITLE
bev_semantics_augmented/0039.png size is 0

### ISSUE THREAD

**Issue by buaazeus** [autonomousvision/carla_garage#28]
The size of following file is 0, will cause issue during training.
s1_dataset_2023_05_10/Routes_Town04_Scenario1_Repetition2/Town04_Scenario1_route49_05_11_16_31_34/bev_semantics_augmented/0039.png
Any chance to update it?
Thank you.
Related issue - https://github.com/autonomousvision/carla_garage/issues/21

**Comment by Kait0** [comment]
Looks like the file is also corrupted in my local copies. Just delete the route folder (s1_dataset_2023_05_10/Routes_Town04_Scenario1_Repetition2/Town04_Scenario1_route49_05_11_16_31_34/) with the file in it, 50 samples won't make a difference.

**Comment by buaazeus** [comment]
Got it, thank you.
