### ISSUE TITLE
Is bb_detected_in_front_of_vehicle in sensor_agent.py be used?

### ISSUE THREAD

**Issue by buaazeus** [autonomousvision/carla_garage#30]
Hello, I wondering if  bb_detected_in_front_of_vehicle is used in sensor_agent.py. If not, the agent is totally controled by the model output, not considering the red light and vehicle bbox detected by ther model, is it so?
I found some red light infraction and vehicle collison of my reproduced model.
Thank you.

**Comment by Kait0** [comment]
The function bb_detected_in_front_of_vehicle is not used. It's a [leftover](https://github.com/autonomousvision/transfuser/blob/22b3ccdb7e806b42c9be2aa476b71546e8ec3620/team_code_transfuser/submission_agent.py#L343) from the transfuser repository where it was used for the latentTF model to replace the LiDAR safety check.

Yes the red light and vehicle bounding box detections are not used during inference. 
The stop sign bounding boxes are optionally used, see [here](https://github.com/autonomousvision/carla_garage/blob/fb4b180332e465c53095ad6de29429442664882c/team_code/sensor_agent.py#L498).
