### ISSUE TITLE
is it possible finetune or retrain the pretened models by using Reinforcement learning, if yes, could you please give some guidelines or references  

### ISSUE THREAD

**Issue by donymorph** [autonomousvision/carla_garage#33]
I am deeply interested in your work, I would like to contribute, because it matches my research field. I successfully ran and evaluated the pretened models on Carla 0.9.14 and leaderboard version 2. I was thinking retrain on top of the pretrained models by using RL such as DQN, PPO, SAC. I have done some RL involved work before but never trained on top of a model that is trained imitation learning

**Comment by Kait0** [comment]
I think it is possible, yes, but not easy, and it requires a substantial engineering commitment to get RL to work with the CARLA leaderboard. There is some open source RL code for CARLA, but unfortunately none that is compatible with the CARLA leaderboard yet.

As for literature, we wrote a paragraph on RL + AD in our [End-to-End driving survey](https://arxiv.org/abs/2306.16927).
The relevant CARLA + RL works you should be aware of are:

https://arxiv.org/abs/1807.03776
https://arxiv.org/abs/1911.10868
https://arxiv.org/abs/2111.08575
https://arxiv.org/abs/2108.08265
https://arxiv.org/abs/2402.16720

Depending on how familiar you are with RL, the recent RL [tutorial](https://arxiv.org/abs/2312.08365) we wrote might also be helpful to you.
