### ISSUE TITLE
Sensor error with PlanT

### ISSUE THREAD

**Issue by djuneja17** [autonomousvision/carla_garage#41]
Hi,
I am running PlanT through the `local_evaluation.sh` file, using leaderboard and scenario_runner. I am running this on Town02 route. It runs fine on the first route but gives the following error at the start of the second route:
```
An exception occurred: 'ServerSideSensor' object is not callable
carla_garage/leaderboard/leaderboard/envs/sensor_interface.py(270)get_data():                                                      
raise SensorReceivedNoData("A sensor took too long to send their data")
```

Could you please let me know how to resolve this issue?

**Comment by Kait0** [comment]
That is a random error. You can just rerun the crashed route.
Discussed something similar [here](https://github.com/autonomousvision/transfuser/issues/216) in case it is helpful.
