### ISSUE TITLE
Question about PDM-Lite on Bench2Drive

### ISSUE THREAD

**Issue by woxihuanjiangguo** [autonomousvision/carla_garage#45]
Hello, i can see that you include the PDM-Lite's results of Bench2Drive in your table. Is the Bench2Drive split used here the same as [this one with 220 routes](https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/leaderboard/data/bench2drive220.xml)?

**Comment by Jens21** [comment]
Hi,

yes, we used [this one with 220 routes](https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/leaderboard/data/bench2drive220.xml). For faster evaluation we split it, that we have one file per route.

Best,
Jens
