### ISSUE TITLE
Can't run aim_02_05_withheld_# models

### ISSUE THREAD

**Issue by MasoudJTehrani** [autonomousvision/carla_garage#49]
Hello, I can't run the "aim" models in the LAV pre-trained weights. I can run the "tfpp_02_05_withheld_#" in the LAV folder by exporting the explained environment variables, but not the "aim" models.
ValueError: An output representation was chosen that was not trained.

Can you tell me how I could do so? do I need other environment variables?

**Comment by Kait0** [comment]
Set the DIRECT variable to 0. Aim is a waypoint model.

`export DIRECT=0`
